export type User = {
  id: number;
  name: string;
  pronunciation: string;
  email: string;
  phone: string;
  nonJapanese: boolean;
  prefectureId: number;
  prefectureOther: string;
  city: string;
  address: string;
  building: string;
  belongId: number;
  belongOther: string;
  belongDetail: string;
  jobId: number;
  jobOther: string;
  foundId: number;
  foundOther: string;
  comments: string;
  warnings: string;
  createdAt: string;
  updatedAt: string;
};
